// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNua27T7p4HQRjgnwIBA44xdYTAZ0N0M',
    appId: '1:931469091217:web:98bb26fda663cb91c53a30',
    messagingSenderId: '931469091217',
    projectId: 'yazlab-2022',
    authDomain: 'yazlab-2022.firebaseapp.com',
    storageBucket: 'yazlab-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5hEV4tHYBRuba5ToGBupTLU5gwnHuVpI',
    appId: '1:931469091217:android:379f32dc0342e37ec53a30',
    messagingSenderId: '931469091217',
    projectId: 'yazlab-2022',
    storageBucket: 'yazlab-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR9jGO-m-csL2B9-FbUna_ASWitO_P7dI',
    appId: '1:931469091217:ios:faf5e482869eaecac53a30',
    messagingSenderId: '931469091217',
    projectId: 'yazlab-2022',
    storageBucket: 'yazlab-2022.appspot.com',
    iosClientId: '931469091217-0pk5d9u2svavtnv40pucah7rao770eph.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazLab1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR9jGO-m-csL2B9-FbUna_ASWitO_P7dI',
    appId: '1:931469091217:ios:faf5e482869eaecac53a30',
    messagingSenderId: '931469091217',
    projectId: 'yazlab-2022',
    storageBucket: 'yazlab-2022.appspot.com',
    iosClientId: '931469091217-0pk5d9u2svavtnv40pucah7rao770eph.apps.googleusercontent.com',
    iosBundleId: 'com.example.yazLab1',
  );
}
